# Generated by Django 5.2.3 on 2025-06-15 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrafficVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('direction', models.CharField(choices=[('NS', 'North to South'), ('SN', 'South to North'), ('EW', 'East to West'), ('WE', 'West to East')], max_length=2)),
                ('volume', models.IntegerField()),
                ('is_simulated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_volumes', to='traffic.intersection')),
            ],
            options={
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['intersection', 'datetime'], name='traffic_tra_interse_34ed1d_idx'), models.Index(fields=['direction'], name='traffic_tra_directi_cd0ba7_idx')],
            },
        ),
    ]
