# Generated by Django 5.2.3 on 2025-06-16 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalTrafficVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('total_volume', models.IntegerField()),
                ('average_speed', models.FloatField()),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic.intersection')),
            ],
            options={
                'db_table': 'total_traffic_volume',
                'indexes': [models.Index(fields=['intersection', 'datetime'], name='total_traff_interse_875aef_idx')],
            },
        ),
    ]
