# Generated by Django 5.2.3 on 2025-06-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_totaltrafficvolume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_number', models.IntegerField()),
                ('ticket_number', models.IntegerField()),
                ('incident_type', models.CharField(max_length=100)),
                ('incident_detail_type', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('managed_by', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('operator', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('registered_at', models.DateTimeField()),
                ('last_status_update', models.DateTimeField()),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
