# Generated by Django 5.2.3 on 2025-06-18 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='intersection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic.intersection'),
        ),
    ]
